name: Cloud SQL Deployment

on:
 push:
   branches:
     - TestBranch

env:
 PROJECT_ID: first-footing-391206
 INSTANCE_NAME: mygcpdb
 DATABASE_NAME: postgres
 GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}

jobs:
 deploy:
   runs-on: selfhostedagent

   steps:
     - name: Checkout code
       uses: actions/checkout@v2

     - name: Set up gcloud
       uses: google-github-actions/setup-gcloud@v0
       with:
         service_account_key: ${{ env.GCP_SA_KEY }}
         project_id: ${{ env.PROJECT_ID }}

     - name: Set up PostgreSQL client
       run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client

     - name: Execute SQL script
       run: |
          sudo ls -lrt
          #psql -h 35.188.198.190 -U postgres -d postgres -p 5432 -f db_scripts/sample.sql
