name: Cloud SQL Deployment

on:
 push:
   branches:
     - TestBranch

env:
 PROJECT_ID: first-footing-391206
 INSTANCE_NAME: mygcpdb
 DATABASE_NAME: postgres
 GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}

jobs:
 deploy:
   runs-on: ubuntu-latest

   steps:
     - name: Checkout code
       uses: actions/checkout@v2

     - name: Set up gcloud
       uses: google-github-actions/setup-gcloud@v0
       with:
         service_account_key: ${{ env.GCP_SA_KEY }}
         project_id: ${{ env.PROJECT_ID }}

     - name: Deploy Cloud SQL
       run: |
         gcloud sql instances create $INSTANCE_NAME --database-version=POSTGRES_14 --region=us-central1
         gcloud sql databases create $DATABASE_NAME --instance=$INSTANCE_NAME

     - name: Run database scripts
       run: |
         for file in db_scripts/*.sql
         do
           gcloud sql import sql $INSTANCE_NAME $file
         done
