name: Cloud SQL Deployment

on:
 push:
   branches:
     - TestBranch

env:
 PROJECT_ID: first-footing-391206
 INSTANCE_NAME: mygcpdb
 DATABASE_NAME: postgres
 GCP_SA_KEY: ${{ secrets.GCP_TEST_NEW }}

jobs:
 deploy:
   runs-on: ubuntu-latest

   steps:
     - name: Checkout code
       uses: actions/checkout@v2

     - name: Set up gcloud
       uses: google-github-actions/setup-gcloud@v0
       with:
         service_account_key: ${{ env.GCP_TEST_NEW }}
         project_id: ${{ env.PROJECT_ID }}
         
     - id: 'auth'
       name: 'Authenticate to Google Cloud'
       uses: 'google-github-actions/auth@v1'
       with:
         credentials_json: ${{ secrets.GCP_TEST_NEW }}
         
     - name: Set up PostgreSQL client
       run: |
          #sudo curl -o cloud-sql-proxy https://storage.googleapis.com/cloud-sql-connectors/cloud-sql-proxy/v2.5.0/cloud-sql-proxy.linux.amd64
          #sudo chmod +x cloud-sql-proxy
          #sudo ./cloud-sql-proxy -
          sudo apt-get update
          sudo apt-get install -y postgresql-client

     - name: Execute SQL script
       run: |
         
          #sudo ./cloud-sql-proxy first-footing-391206:us-central1:mygcpdb 
          #gcloud sql connect mygcpdb --user=postgres 
          PGPASSWORD=Shab@123456 psql -U postgres --host=35.188.198.190
