name: Deployment

# on commit push, run job
on:
  push:
   branches:
      - TestBranch
jobs:
  run:
    # worker runs on latest ubuntu
    runs-on: ubuntu-latest

    steps:
    # checkout to our repository so we have access to the source code
    - uses: actions/checkout@v2
    
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0'
      with:
        workload_identity_provider: 'projects/45358373180/locations/global/workloadIdentityPools/mypoolid/providers/myprovider123'
        service_account: 'git-deployer@first-footing-391206.iam.gserviceaccount.com'
    # the actual deployment to google
    - name: Cloud Functions Deploy
      uses: google-github-actions/deploy-cloud-functions@v1.0.1
      with:
        credentials: $GCP_SA_KEY
        name: myapp
        description: Test python cloud function # nullable
        project_id: first-footing-391206
        region: us-central1
        source_dir: src
        # name of our function in our main.py file, defaults to the resource name suffix 
        entry_point: hello_world
        # runtime to use for the function
        runtime: python39
        # the function execution timeout
        timeout: 60
        # the maximum number of instances for the function.
        max_instances: 1
        # optional configs, see google-cloud-actions/deploy-cloud-functions for full reference
        # list of key-value pairs to set as environment variables in the form KEY1=VALUE1,KEY2=VALUE2.
#       env_vars: # optional
