name: Deployment

# on commit push, run job
on:
  push:
   branches:
      - TestBranch
jobs:
  run:
    # worker runs on latest ubuntu
    runs-on: ubuntu-latest

    steps:
    # checkout to our repository so we have access to the source code
    - uses: actions/checkout@v2
    
    # the actual deployment to google
    - name: Cloud Functions Deploy
      uses: google-github-actions/deploy-cloud-functions@v1
      with:
        credentials: nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDXYlhapMsdF8OQ\nBzAvzSSeEYYczCt8L1eQqTUrwq1zZMYuvnAfik/7dvpVlO1EGLPPVyCNoabSrbac\nortdvYjQqGORk7sBRPoQBfKEOnpz4uXhgF5DG4ZQd4ekpXSjBoDY2KijfJJRes/X\nq+nTnwLITFGpqoK1eLXtW4EyM5+fThsrAdRC18R3G9UphYYDLgclMVPawzaRqN51\n1sK8Eu+jGF41enXu/UmifTvB3jGIjba4WCRLKwmkPSOJE2r6saKAkuzB24WPMNso\njl/tgdwu7RxpfTsW30lNZGoU+NEG2wYRty2xA7Vz14gN0bQrWkm5D7WWxQOzhBsb\neivxBsUZAgMBAAECggEAKq/YVICwK8Art2YhT/v/q59L/fWeEbL9TxOmENn4z/Oz\nTozaQnoCX5OFSkRloNcnfeql7kQRQNSCanlbGplHnhkdgLrvd3ExAU94cOn5HnIj\n/uUW6YRxQo3qEYDkRLIzg6avB5XXFvR48GTnRxSO890iWzbKyIYXwmbeDHHMS0FN\nnZDYB8boCsbXG1DDAGS2PMXm4X6AsjuxP8dMuIqWLp6IAH6DvnotP+7lmrSkwx9h\nG6V/airL7bbIg97wX//q70ebYmrmWrPG5XxtC7fJZF3EFTa/z35CeDtsXtHUQH0n\n1XECgBaLi0vQmV/apwdSv7nXjfdgX7D4SkJYsKRXDQKBgQD6kWREdSfR33lQd+Ph\nRaVxY4eausFYQcxUXQSK1SdnQkoCYP4KtqnfTN3bBrG9iWKlPwZJlMR7pWcIFj4I\ngNM/fJ+l1+MRuxoWzim4gyngGH5LQaM92yJkjttinVss6CEyvHcHQKufuHpnT5P6\nVLAcljt59gznqlyLHsvkUeBptQKBgQDcDbCMwEV57ZCncsGXULL7b/mLBFt7roDM\nMWDJO27DW/pfTGH205fElNtvvODoYplkTU/DkgmfhZSGVFRLGNayTWQ5JDxTfkWT\nJf6RlZ5wR/qmqaVa19buKl9K5eaI5mnCfUxU6V5YTatOofWHrjY19wImdDExNQui\neEuThxB8VQKBgQCig24u4HWFL5Y1VK0eTNezJUSsXHhOT87A4NuzV/CIjnwF8vaR\n6EthIy+5gSwCrHqohqoDS1Pshii/G/378eIRiTjajZ0ewOV46RoyLBAa4of3M4k2\n80vpQKaV3U1nYN83Uvk4YP9vRm1NWFW3xPm8cMv+nFFeaCZBrSW83kXZCQKBgByc\nZw0V3rKosbsjz4nmAy9v8qkhiud82+Awt13SrWcXKWmEm+QkxMHZfOJ9U1zDnSAO\ncUWDUl78VkBU7JTLCPcr2tEXJgTRESi9suio5G3C3hMXUZmLILXcqoEpfRzloHCa\nK/eKVCr1BkX2Bt96RjAkCpKHXvH/7KBWNbVbxUf1AoGAXLp8cY+TG89vAWj7P2yG\nqgtb26Z0qIYDlajWqx2kiObhFxWdD2NEBP5QQSiKz0W1bgio5or/D7ou2Lb9L9Cj\n57c3oQJ0cbXHb5nrqpbwriUK8EX7ok09JOzXbDzhovNoSgg2F0TS1yM9l2XNakD1\nUwmz+B7lVGBBRX2wJ+MqKZw=
        name: myapp
        description: Test python cloud function # nullable
        project_id: first-footing-391206
        region: us-central1
        source_dir: src
        # name of our function in our main.py file, defaults to the resource name suffix 
        entry_point: hello_world
        # runtime to use for the function
        runtime: python39
        # the function execution timeout
        timeout: 60
        # the maximum number of instances for the function.
        max_instances: 1
        # optional configs, see google-cloud-actions/deploy-cloud-functions for full reference
        # list of key-value pairs to set as environment variables in the form KEY1=VALUE1,KEY2=VALUE2.
#       env_vars: # optional
